name: yasmin

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"

  second-job:
    needs: my-job
    runs-on: ubuntu-latest
    steps:
      - name: dependent-step
        run: echo "This runs after my-job completes!"

